import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#7073ff",
        "inverse-surface": "#303032",
        "tertiary": "#000000",
        "secondary-fixed": "#d8e2ff",
        "on-secondary": "#ffffff",
        "on-background": "#1b1b1d",
        "on-tertiary": "#ffffff",
        "secondary": "#0058be",
        "outline": "#76777d",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "primary-fixed": "#dae2fd",
        "surface-variant": "#e4e2e4",
        "on-primary-container": "#7c839b",
        "inverse-primary": "#bec6e0",
        "tertiary-container": "#07006c",
        "on-secondary-fixed": "#001a42",
        "error": "#ba1a1a",
        "surface-dim": "#dcd9db",
        "surface-tint": "#565e74",
        "primary": "#000000",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-highest": "#e4e2e4",
        "tertiary-fixed": "#e1e0ff",
        "secondary-container": "#2170e4",
        "background": "#fcf8fa",
        "surface-container-high": "#eae7e9",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#c6c6cd",
        "on-secondary-container": "#fefcff",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf8fa",
        "on-error-container": "#93000a",
        "primary-container": "#131b2e",
        "inverse-on-surface": "#f3f0f2",
        "on-surface-variant": "#45464d",
        "on-tertiary-fixed": "#07006c",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface": "#fcf8fa",
        "on-surface": "#1b1b1d",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-low": "#f6f3f5",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0edef",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "2.5rem",
        xl: "2rem",
        "margin-mobile": "1rem",
        md: "1rem",
        lg: "1.5rem",
        sm: "0.5rem",
        "2xl": "3rem",
        xs: "0.25rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "title-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "code-mono": ["Geist", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "code-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
